# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6d95f96b-a5cc-417f-a975-ace025d3c502";
      fsType = "btrfs";
    };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/6d95f96b-a5cc-417f-a975-ace025d3c502";
    fsType = "btrfs";
    options = [ "subvol=swap" "compress=lzo" "noatime" ];
  };

  swapDevices = [
   {
    device = "/swap/swapfile";
    size = (1024 * 2);
  }
 ];

}
